#!/usr/bin/env bash

sudo apt -y update
sudo apt -y install git ripgrep pavucontrol xclip jq tldr shutter python3-pip python3-venv

git clone git@github.com:junegunn/fzf.git $HOME/personal/fzf
$HOME/personal/fzf/install
